apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    app: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: yehudalinker/service-b:v1
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          value: redis-0.redis-svc
        - name: REDIS_PORT
          value: "6379"
